chargebee/urls.py
from django.urls import path
from . import views


app_name = 'chargebee'

urlpatterns = [
    path('', views.index, name='index'),
    path('subscribe-now', views.subscribe_now, name='subscribe_now'),
    path('customer-portal', views.customer_portal, name='customer_portal'),
]

python_subscription_management/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chargebee/', include('chargebee.urls')),
]

chargebee/models.py
from django.db import models

# Create your models here.

chargebee/views.py
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import render


def index(request):
    template = loader.get_template('chargebee/index.html')
    return HttpResponse(template.render({}, request))


def subscribe_now(request):
    return render(request, 'chargebee/subscribe_now.html')


def customer_portal(request):
    return render(request, 'chargebee/customer_portal.html')

chargebee/templates/chargebee/customer_portal.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Subscription Management - Chargebee - Customer Portal</title>
        <meta charset="utf-8">
        {# TODO REPLACE SITE WITH ENVIRONMENT VARIABLE #}
        <script src = "https://js.chargebee.com/v2/chargebee.js"  data-cb-site = "rubenvilar-test" > </script>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    <li><a href="{% url 'chargebee:index' %}">Index</a></li>
                </ul>
            </nav>
        </header>
        <main>
            <section>
                <a href="javascript:void(0)" data-cb-type="portal" >Open Customer Portal</a>
            </section>
        </main>
        <footer></footer>
    </body>
</html>

chargebee/templates/chargebee/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Subscription Management - Chargebee</title>
        <meta charset="utf-8">
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    <li><a href="{% url 'chargebee:subscribe_now' %}">Subscribe Now</a></li>
                    <li><a href="{% url 'chargebee:customer_portal' %}">Customer Portal</a></li>
                </ul>
            </nav>
        </header>
        <main>
            <section></section>
        </main>
        <footer></footer>
    </body>
</html>

chargebee/templates/chargebee/subscribe_now.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Subscription Management - Chargebee - Subscribe Now</title>
        <meta charset="utf-8">
        {# TODO REPLACE SITE WITH ENVIRONMENT VARIABLE #}
        <script src = "https://js.chargebee.com/v2/chargebee.js"  data-cb-site = "rubenvilar-test" > </script>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    <li><a href="/chargebee">Index</a></li>
                </ul>
            </nav>
        </header>
        <main>
            <section>
                <a href = "javascript:void(0)"  data-cb-type = "checkout"  data-cb-plan-id = "cbdemo_free" > Open Checkout </a>
            </section>
        </main>
        <footer></footer>
    </body>
</html>